version: '3'

services:
  
  nagios:
    image: jasonrivers/nagios:latest
    volumes:
      - nagiosetc:/opt/nagios/etc
      - nagiosvar:/opt/nagios/var
      - customplugins:/opt/Custom-Nagios-Plugins
      - nagiosgraphvar:/opt/nagiosgraph/var
      - nagiosgraphetc:/opt/nagiosgraph/etc
    ports:
      - "8080:80"
    restart: always    

volumes:
  nagiosetc:
  nagiosvar:
  customplugins:
  nagiosgraphvar:
  nagiosgraphetc:
